import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Shell, Card } from "@/components/Layout";
import { RequireAuth } from "@/components/RequireAuth";
import { useAppState } from "@/lib/store";
import { suggestGigs, gigApplyLinks } from "@/lib/ai";
import { useDisplayUser } from "@/lib/useDisplayUser";
import { generateRoadmap } from "@/lib/roadmap.functions";

export const Route = createFileRoute("/sprint")({
  head: () => ({
    meta: [
      { title: "7-Day AI Sprint — EARNGEN-AI" },
      { name: "description", content: "Real-time AI-generated 7-day plan with outreach scripts, YouTube learning links, and Fiverr/Unstop apply links." },
    ],
  }),
  component: Sprint,
});

function Sprint() {
  const { state, toggleDay } = useAppState();
  const me = useDisplayUser();
  const [copied, setCopied] = useState<string | null>(null);
  const fetchRoadmap = useServerFn(generateRoadmap);

  if (!state.sprint) {
    return (
      <Shell>
        <RequireAuth>
        <Card className="p-12 text-center">
          <h1 className="text-2xl font-semibold tracking-tight">No active sprint</h1>
          <p className="text-muted-foreground mt-2 mb-6">Pick a gig to generate your real-time AI 7-day execution plan.</p>
          <Link to="/opportunities" className="inline-flex bg-brand text-brand-foreground font-semibold px-5 py-2.5 rounded-lg">
            Browse opportunities →
          </Link>
        </Card>
        </RequireAuth>
      </Shell>
    );
  }

  const gigs = suggestGigs(state.skills, me.city, me.name);
  const gig = gigs.find((g) => g.title === state.sprint!.gigTitle) ?? gigs[0];
  const links = useMemo(() => gigApplyLinks(gig.title, me.city), [gig.title, me.city]);

  const topicSkills =
    gig.matchedSkills.length > 0 ? gig.matchedSkills : state.skills.length ? state.skills : ["General freelancing"];

  const { data, isLoading, isError, refetch, isFetching } = useQuery({
    queryKey: ["roadmap", gig.id, topicSkills.join(","), me.city, me.name],
    queryFn: () =>
      fetchRoadmap({
        data: {
          gigTitle: gig.title,
          description: gig.description,
          skills: topicSkills,
          city: me.city || "India",
          name: me.name || "there",
          platforms: gig.platforms,
          minPrice: gig.minPrice,
          maxPrice: gig.maxPrice,
        },
      }),
    staleTime: 0,
    gcTime: 1000 * 60 * 5,
    refetchOnWindowFocus: true,
  });

  const plan = data?.days ?? [];
  const completed = state.sprint.completedDays;
  const pct = plan.length ? Math.round((completed.length / plan.length) * 100) : 0;

  function copy(s: string, key: string) {
    navigator.clipboard.writeText(s);
    setCopied(key);
    setTimeout(() => setCopied(null), 1500);
  }

  return (
    <Shell>
      <RequireAuth>
      <header className="mb-8 fade-up">
        <p className="text-xs font-semibold text-brand uppercase tracking-widest">7-Day AI Sprint</p>
        <h1 className="text-3xl font-semibold tracking-tight mt-2">{gig.title}</h1>
        <p className="text-muted-foreground mt-2 max-w-[60ch] text-pretty">{gig.description}</p>

        <div className="flex flex-wrap gap-2 mt-4">
          <a href={links.fiverr} target="_blank" rel="noopener noreferrer" className="text-xs font-semibold rounded-md ring-1 ring-border px-2.5 py-1 hover:bg-muted">Apply on Fiverr ↗</a>
          <a href={links.unstop} target="_blank" rel="noopener noreferrer" className="text-xs font-semibold rounded-md ring-1 ring-border px-2.5 py-1 hover:bg-muted">Find on Unstop ↗</a>
          <a href={links.youtube} target="_blank" rel="noopener noreferrer" className="text-xs font-semibold rounded-md ring-1 ring-border px-2.5 py-1 hover:bg-muted">Learn on YouTube ↗</a>
        </div>

        <div className="mt-6 max-w-md">
          <div className="flex items-center justify-between text-xs font-medium mb-2">
            <span>{completed.length}/{plan.length || 7} days · 🔥 streak</span>
            <span className="text-brand">{pct}% to ₹1,000</span>
          </div>
          <div className="h-2 rounded-full bg-muted overflow-hidden">
            <div className="h-full bg-brand transition-all" style={{ width: `${pct}%` }} />
          </div>
          <div className="flex items-center gap-3 mt-3 text-[11px] text-muted-foreground">
            {isLoading || isFetching ? (
              <span className="inline-flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-brand pulse-dot" /> AI is generating your plan in real time…</span>
            ) : data?.source === "ai" ? (
              <span>✨ Plan generated by AI for your skills · <button onClick={() => refetch()} className="underline hover:text-foreground">Regenerate</button></span>
            ) : (
              <span>Showing baseline plan{data?.error ? ` (${data.error})` : ""} · <button onClick={() => refetch()} className="underline hover:text-foreground">Try AI again</button></span>
            )}
          </div>
        </div>
      </header>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-4">
          {isLoading && plan.length === 0 ? (
            <>
              {[1, 2, 3, 4].map((i) => <div key={i} className="h-28 rounded-2xl bg-muted animate-pulse" />)}
            </>
          ) : isError ? (
            <Card className="p-6">
              <p className="font-semibold">Couldn't generate the plan.</p>
              <button onClick={() => refetch()} className="mt-3 text-sm font-semibold text-brand hover:underline">Retry →</button>
            </Card>
          ) : (
            plan.map((step, i) => {
              const done = completed.includes(step.day);
              const active = !done && completed.length === i;
              return (
                <Card key={step.day} className={"p-5 transition-all " + (active ? "ring-2 ring-brand" : "")}>
                  <div className="flex items-start gap-4">
                    <button
                      onClick={() => toggleDay(step.day)}
                      className={"mt-0.5 size-6 rounded-full grid place-items-center text-xs font-bold ring-2 transition-colors " + (done ? "bg-brand text-brand-foreground ring-brand" : "bg-card text-muted-foreground ring-border hover:ring-brand")}
                      aria-label={`Toggle day ${step.day}`}
                    >
                      {done ? "✓" : step.day}
                    </button>
                    <div className="flex-1">
                      <p className={"text-[10px] font-semibold uppercase tracking-widest " + (done || active ? "text-brand" : "text-muted-foreground")}>
                        Day {step.day} {done ? "· Complete" : active ? "· Active" : ""}
                      </p>
                      <h3 className={"font-semibold mt-1 " + (done ? "line-through text-muted-foreground" : "")}>{step.title}</h3>
                      <p className="text-sm text-muted-foreground mt-1 text-pretty">{step.detail}</p>
                      {step.youtube && step.youtube.length > 0 && (
                        <div className="mt-3 flex flex-wrap gap-2">
                          {step.youtube.map((y, idx) => (
                            <a key={idx} href={y.url} target="_blank" rel="noopener noreferrer" className="text-xs font-medium rounded-md bg-destructive/10 text-destructive ring-1 ring-destructive/20 px-2.5 py-1 hover:bg-destructive/15">
                              ▶ {y.query}
                            </a>
                          ))}
                        </div>
                      )}
                      {step.script && (
                        <div className="mt-4 rounded-xl bg-muted p-4">
                          <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground mb-2">AI-written outreach</p>
                          <p className="text-sm italic text-foreground">"{step.script}"</p>
                          <button onClick={() => copy(step.script!, `d${step.day}`)} className="mt-3 text-xs font-semibold text-brand hover:underline">
                            {copied === `d${step.day}` ? "✓ Copied!" : "Copy message →"}
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                </Card>
              );
            })
          )}
        </div>

        <aside className="space-y-4">
          <Card className="p-6">
            <h3 className="font-semibold">Sprint summary</h3>
            <dl className="mt-4 space-y-3 text-sm">
              <div className="flex justify-between"><dt className="text-muted-foreground">Target payout</dt><dd className="font-semibold">₹{gig.minPrice.toLocaleString("en-IN")}–₹{gig.maxPrice.toLocaleString("en-IN")}</dd></div>
              <div className="flex justify-between"><dt className="text-muted-foreground">Difficulty</dt><dd className="font-semibold">{gig.difficulty}</dd></div>
              <div className="flex justify-between"><dt className="text-muted-foreground">Platforms</dt><dd className="font-semibold text-right">{gig.platforms.join(", ")}</dd></div>
              <div className="flex justify-between"><dt className="text-muted-foreground">Days to first ₹</dt><dd className="font-semibold">~{gig.daysToFirstEarn}</dd></div>
            </dl>
          </Card>
          <Card className="p-6 bg-foreground text-background ring-foreground">
            <p className="text-xs font-semibold uppercase tracking-widest text-brand-light">After day 7</p>
            <h3 className="font-semibold mt-2">Log your payment.</h3>
            <p className="text-sm text-background/70 mt-2">When you collect, head to Income and log it. We'll mint a verified Proof-of-Work automatically.</p>
            <Link to="/income" className="inline-flex mt-4 text-sm font-semibold text-brand-light">Go to Income →</Link>
          </Card>
        </aside>
      </div>
      </RequireAuth>
    </Shell>
  );
}
