import type { LiveEvent } from "./types";

/**
 * Direct links to platform pages that list ONGOING hackathons, internships, and events.
 * These always work — students land on live registration listings, not stale API rows.
 */
export const ONGOING_PORTAL_LINKS: LiveEvent[] = [
  {
    id: "portal-devfolio",
    source: "devfolio",
    title: "Devfolio — Open hackathons",
    organizer: "Devfolio",
    type: "hackathon",
    description: "India’s largest hackathon discovery. Filter by online/offline, theme, and registration status.",
    tagline: "Registration open now",
    applyUrl: "https://devfolio.co/hackathons",
    skillTags: ["hackathon", "ai", "startup", "coding"],
    isOnline: true,
    matchPercent: 95,
    trendingScore: 99,
    registrationDeadline: undefined,
  },
  {
    id: "portal-unstop-hack",
    source: "unstop",
    title: "Unstop — Live hackathons",
    organizer: "Unstop",
    type: "hackathon",
    description: "Ongoing hackathons with prizes, teams, and deadlines — updated daily.",
    tagline: "Apply directly on Unstop",
    applyUrl: "https://unstop.com/hackathons",
    skillTags: ["hackathon", "competition", "startup"],
    isOnline: true,
    matchPercent: 94,
    trendingScore: 98,
  },
  {
    id: "portal-unstop-intern",
    source: "unstop",
    title: "Unstop — Internships hiring now",
    organizer: "Unstop",
    type: "internship",
    description: "Paid internships and fellowships for students — filter by skill and city.",
    applyUrl: "https://unstop.com/internships",
    skillTags: ["internship", "remote job"],
    isOnline: true,
    matchPercent: 92,
    trendingScore: 96,
  },
  {
    id: "portal-unstop-comp",
    source: "unstop",
    title: "Unstop — Competitions & challenges",
    organizer: "Unstop",
    type: "coding_competition",
    description: "Case competitions, coding contests, and brand challenges with cash prizes.",
    applyUrl: "https://unstop.com/competitions",
    skillTags: ["competition", "business", "design"],
    isOnline: true,
    matchPercent: 90,
    trendingScore: 94,
  },
  {
    id: "portal-hackerearth",
    source: "earngen",
    title: "HackerEarth — Active hackathons",
    organizer: "HackerEarth",
    type: "hackathon",
    description: "Browse hackathons with open registration and leaderboards.",
    applyUrl: "https://www.hackerearth.com/challenges/hackathon/",
    skillTags: ["coding", "hackathon", "ai"],
    isOnline: true,
    matchPercent: 88,
    trendingScore: 92,
  },
  {
    id: "portal-d2c",
    source: "earngen",
    title: "Dare2Compete — Hackathons",
    organizer: "Dare2Compete",
    type: "hackathon",
    description: "College hackathons, B-plan contests, and national competitions.",
    applyUrl: "https://dare2compete.com/hackathons",
    skillTags: ["hackathon", "startup", "competition"],
    isOnline: false,
    matchPercent: 87,
    trendingScore: 90,
  },
  {
    id: "portal-internshala",
    source: "earngen",
    title: "Internshala — Internships",
    organizer: "Internshala",
    type: "internship",
    description: "Work-from-home and in-office internships for Indian students.",
    applyUrl: "https://internshala.com/internships",
    skillTags: ["internship", "remote job"],
    isOnline: true,
    matchPercent: 91,
    trendingScore: 93,
  },
  {
    id: "portal-meetup",
    source: "earngen",
    title: "Meetup — Tech & startup events near you",
    organizer: "Meetup",
    type: "networking",
    description: "Find hackathons, meetups, and networking events in your city this week.",
    applyUrl: "https://www.meetup.com/find/?keywords=hackathon%20startup%20ai%20tech",
    skillTags: ["networking", "meetup", "community"],
    isOnline: false,
    matchPercent: 85,
    trendingScore: 88,
  },
  {
    id: "portal-eventbrite",
    source: "earngen",
    title: "Eventbrite — Tech events India",
    organizer: "Eventbrite",
    type: "workshop",
    description: "Workshops, demo days, and conferences with tickets and RSVP links.",
    applyUrl: "https://www.eventbrite.com/d/india/technology--events/",
    skillTags: ["workshop", "demo day", "networking"],
    isOnline: false,
    matchPercent: 84,
    trendingScore: 86,
  },
  {
    id: "portal-github",
    source: "earngen",
    title: "GitHub — Community events",
    organizer: "GitHub",
    type: "community",
    description: "Virtual and in-person open-source and developer community events.",
    applyUrl: "https://github.com/events",
    skillTags: ["open source", "coding", "community"],
    isOnline: true,
    matchPercent: 82,
    trendingScore: 85,
  },
  {
    id: "portal-linkedin",
    source: "earngen",
    title: "LinkedIn — Jobs & internships",
    organizer: "LinkedIn",
    type: "internship",
    description: "Filter remote internships and early-career roles — apply on company pages.",
    applyUrl: "https://www.linkedin.com/jobs/search/?keywords=internship%20remote&f_TPR=r604800",
    skillTags: ["internship", "remote job", "startup"],
    isOnline: true,
    matchPercent: 86,
    trendingScore: 87,
  },
  {
    id: "portal-producthunt",
    source: "earngen",
    title: "Product Hunt — Launches & maker events",
    organizer: "Product Hunt",
    type: "startup_event",
    description: "Discover startup launches, AMAs, and maker community happenings.",
    applyUrl: "https://www.producthunt.com/",
    skillTags: ["startup", "creator", "ai"],
    isOnline: true,
    matchPercent: 80,
    trendingScore: 84,
  },
];
