import type { Course } from "./types";

const yt = (id: string) => `https://img.youtube.com/vi/${id}/hqdefault.jpg`;

/** Curated high-quality YouTube learning paths — expand with YouTube Data API when YOUTUBE_API_KEY is set */
export const COURSE_CATALOG: Course[] = [
  {
    id: "prompt-eng-freecodecamp",
    title: "Prompt Engineering Full Course",
    creator: "freeCodeCamp.org",
    category: "Prompt Engineering",
    description: "Complete prompt engineering for ChatGPT, Claude, and LLM apps — from basics to advanced chains.",
    thumbnail: yt("_ZvnD73m40o"),
    difficulty: "Beginner",
    durationHours: 4,
    rating: 4.8,
    views: "2.1M+",
    youtubePlaylistId: "PL4cUxeDkc8fgP9G0yNE0pZ3n0XyH4Kq",
    youtubeVideoId: "_ZvnD73m40o",
    lessons: [
      { id: "l1", title: "Intro to prompt engineering", youtubeVideoId: "_ZvnD73m40o", durationMin: 45 },
      { id: "l2", title: "Few-shot & chain-of-thought", youtubeVideoId: "wbGKfAPlZVA", durationMin: 38 },
    ],
    tags: ["ai", "prompt", "chatgpt", "llm"],
    earningTags: ["ai", "freelance", "content"],
    projectIdeas: ["AI client chatbot", "Prompt template pack on Gumroad"],
    free: true,
  },
  {
    id: "figma-ui-ux",
    title: "Figma UI/UX Design Tutorial",
    creator: "Flux Academy",
    category: "UI/UX Design",
    description: "Design modern interfaces in Figma — components, auto-layout, and handoff for developers.",
    thumbnail: yt("FTFa7WcAD7E"),
    difficulty: "Beginner",
    durationHours: 6,
    rating: 4.7,
    views: "890K+",
    youtubeVideoId: "FTFa7WcAD7E",
    lessons: [
      { id: "l1", title: "Figma fundamentals", youtubeVideoId: "FTFa7WcAD7E", durationMin: 52 },
      { id: "l2", title: "Design system basics", youtubeVideoId: "jwCmIBJ8Jtc", durationMin: 40 },
    ],
    tags: ["figma", "ui", "ux", "design"],
    earningTags: ["design", "freelance", "startup"],
    projectIdeas: ["3-screen mobile app UI", "SaaS landing page in Figma"],
    free: true,
  },
  {
    id: "canva-design",
    title: "Canva for Beginners — Social & Brand Design",
    creator: "Ronny Hermosa",
    category: "Graphic Design",
    description: "Create scroll-stopping social posts, brand kits, and thumbnails with Canva AI tools.",
    thumbnail: yt("A0vjXV8l8gE"),
    difficulty: "Beginner",
    durationHours: 3,
    rating: 4.6,
    views: "450K+",
    youtubeVideoId: "A0vjXV8l8gE",
    lessons: [{ id: "l1", title: "Canva workspace & brand kit", youtubeVideoId: "A0vjXV8l8gE", durationMin: 35 }],
    tags: ["canva", "design", "social media"],
    earningTags: ["design", "creator", "freelance"],
    projectIdeas: ["10 Instagram templates to sell", "Cafe brand kit"],
    free: true,
  },
  {
    id: "react-full",
    title: "React.js Full Course",
    creator: "freeCodeCamp.org",
    category: "Web Development",
    description: "Build modern web apps with React, hooks, and real projects from scratch.",
    thumbnail: yt("SqcY0GlETPk"),
    difficulty: "Intermediate",
    durationHours: 11,
    rating: 4.9,
    views: "8M+",
    youtubeVideoId: "SqcY0GlETPk",
    lessons: [
      { id: "l1", title: "React setup & JSX", youtubeVideoId: "SqcY0GlETPk", durationMin: 60 },
      { id: "l2", title: "Hooks deep dive", youtubeVideoId: "TNhaISOW2DI", durationMin: 55 },
    ],
    tags: ["react", "javascript", "web"],
    earningTags: ["coding", "freelance", "startup"],
    projectIdeas: ["Portfolio site", "SaaS dashboard MVP"],
    free: true,
  },
  {
    id: "python-data",
    title: "Python for Data Science",
    creator: "freeCodeCamp.org",
    category: "Data Science",
    description: "Python, pandas, visualization, and ML foundations for analysts and builders.",
    thumbnail: yt("LHBE6Q9cKl0"),
    difficulty: "Beginner",
    durationHours: 12,
    rating: 4.8,
    views: "5M+",
    youtubeVideoId: "LHBE6Q9cKl0",
    lessons: [{ id: "l1", title: "Python basics", youtubeVideoId: "LHBE6Q9cKl0", durationMin: 70 }],
    tags: ["python", "data", "ml"],
    earningTags: ["coding", "internship"],
    projectIdeas: ["Kaggle notebook", "Sales dashboard"],
    free: true,
  },
  {
    id: "premiere-edit",
    title: "Premiere Pro for Beginners",
    creator: "Benjamin Anderson",
    category: "Video Editing",
    description: "Edit YouTube videos, reels, and client deliverables with professional workflow.",
    thumbnail: yt("q9XfkryqXjI"),
    difficulty: "Beginner",
    durationHours: 5,
    rating: 4.5,
    views: "1.2M+",
    youtubeVideoId: "q9XfkryqXjI",
    lessons: [{ id: "l1", title: "Timeline & cuts", youtubeVideoId: "q9XfkryqXjI", durationMin: 42 }],
    tags: ["video", "editing", "youtube"],
    earningTags: ["creator", "freelance"],
    projectIdeas: ["30s brand reel", "YouTube intro pack"],
    free: true,
  },
  {
    id: "freelance-guide",
    title: "Freelancing Complete Guide for Students",
    creator: "Ali Abdaal",
    category: "Freelancing",
    description: "Find clients, price projects, and build a sustainable freelance income as a student.",
    thumbnail: yt("52tBA-ajajQ"),
    difficulty: "Beginner",
    durationHours: 2,
    rating: 4.7,
    views: "3M+",
    youtubeVideoId: "52tBA-ajajQ",
    lessons: [{ id: "l1", title: "Freelance foundations", youtubeVideoId: "52tBA-ajajQ", durationMin: 28 }],
    tags: ["freelance", "business", "income"],
    earningTags: ["freelance", "fiverr", "upwork"],
    projectIdeas: ["First Fiverr gig", "Client outreach list"],
    free: true,
  },
  {
    id: "startup-yc",
    title: "How to Start a Startup",
    creator: "Y Combinator",
    category: "Startup Building",
    description: "YC lectures on ideas, MVP, growth, and fundraising for student founders.",
    thumbnail: yt("CBYhVcVi4gY"),
    difficulty: "Intermediate",
    durationHours: 20,
    rating: 4.9,
    views: "1M+",
    youtubeVideoId: "CBYhVcVi4gY",
    lessons: [{ id: "l1", title: "Ideas & execution", youtubeVideoId: "CBYhVcVi4gY", durationMin: 50 }],
    tags: ["startup", "founder", "mvp"],
    earningTags: ["startup", "hackathon"],
    projectIdeas: ["1-page pitch deck", "Landing page MVP"],
    free: true,
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing Course",
    creator: "Simplilearn",
    category: "Marketing",
    description: "SEO, social ads, content marketing, and analytics for brands and creators.",
    thumbnail: yt("ZVuToMilP0A"),
    difficulty: "Beginner",
    durationHours: 8,
    rating: 4.4,
    views: "2M+",
    youtubeVideoId: "ZVuToMilP0A",
    lessons: [{ id: "l1", title: "Marketing fundamentals", youtubeVideoId: "ZVuToMilP0A", durationMin: 45 }],
    tags: ["marketing", "seo", "ads"],
    earningTags: ["marketing", "freelance"],
    projectIdeas: ["Campaign for local business", "Instagram growth plan"],
    free: true,
  },
  {
    id: "flutter-app",
    title: "Flutter Course for Beginners",
    creator: "freeCodeCamp.org",
    category: "App Development",
    description: "Cross-platform mobile apps with Flutter and Dart — one codebase for iOS & Android.",
    thumbnail: yt("VPvVDMSjt10"),
    difficulty: "Intermediate",
    durationHours: 37,
    rating: 4.8,
    views: "4M+",
    youtubeVideoId: "VPvVDMSjt10",
    lessons: [{ id: "l1", title: "Dart & widgets", youtubeVideoId: "VPvVDMSjt10", durationMin: 65 }],
    tags: ["flutter", "mobile", "app"],
    earningTags: ["coding", "freelance"],
    projectIdeas: ["Habit tracker app", "Client booking app"],
    free: true,
  },
  {
    id: "ai-automation",
    title: "AI Automation with Make & Zapier",
    creator: "Nick Saraev",
    category: "Artificial Intelligence",
    description: "Automate workflows with AI — lead gen, content, and client delivery pipelines.",
    thumbnail: yt("w0H1-b044KY"),
    difficulty: "Intermediate",
    durationHours: 4,
    rating: 4.6,
    views: "320K+",
    youtubeVideoId: "w0H1-b044KY",
    lessons: [{ id: "l1", title: "Automation stacks", youtubeVideoId: "w0H1-b044KY", durationMin: 38 }],
    tags: ["ai", "automation", "no-code"],
    earningTags: ["ai", "freelance", "startup"],
    projectIdeas: ["Lead capture automation", "AI email assistant"],
    free: true,
  },
  {
    id: "content-youtube",
    title: "YouTube Creator Academy",
    creator: "YouTube Creators",
    category: "Content Creation",
    description: "Grow a channel — thumbnails, retention, scripting, and monetization basics.",
    thumbnail: yt("XH7p8Vq8q7g"),
    difficulty: "Beginner",
    durationHours: 3,
    rating: 4.5,
    views: "500K+",
    youtubeVideoId: "XH7p8Vq8q7g",
    lessons: [{ id: "l1", title: "Channel strategy", youtubeVideoId: "XH7p8Vq8q7g", durationMin: 30 }],
    tags: ["youtube", "creator", "content"],
    earningTags: ["creator", "passive"],
    projectIdeas: ["10 video ideas doc", "Thumbnail A/B test"],
    free: true,
  },
  {
    id: "cybersec-intro",
    title: "Cybersecurity Full Course",
    creator: "My CS",
    category: "Cybersecurity",
    description: "Security fundamentals, networking, and ethical hacking intro for students.",
    thumbnail: yt("inWWhr5tnEA"),
    difficulty: "Beginner",
    durationHours: 15,
    rating: 4.7,
    views: "1.5M+",
    youtubeVideoId: "inWWhr5tnEA",
    lessons: [{ id: "l1", title: "Security basics", youtubeVideoId: "inWWhr5tnEA", durationMin: 55 }],
    tags: ["security", "hacking", "network"],
    earningTags: ["coding", "internship"],
    projectIdeas: ["Home lab setup", "Vulnerability report write-up"],
    free: true,
  },
  {
    id: "notion-productivity",
    title: "Notion for Students & Creators",
    creator: "Thomas Frank",
    category: "No-Code Tools",
    description: "Build second brain, project trackers, and client portals in Notion.",
    thumbnail: yt("oTahLEX3eR0"),
    difficulty: "Beginner",
    durationHours: 2,
    rating: 4.6,
    views: "800K+",
    youtubeVideoId: "oTahLEX3eR0",
    lessons: [{ id: "l1", title: "Notion workspace", youtubeVideoId: "oTahLEX3eR0", durationMin: 25 }],
    tags: ["notion", "productivity", "no-code"],
    earningTags: ["freelance", "startup"],
    projectIdeas: ["Sell Notion template", "Freelance CRM"],
    free: true,
  },
  {
    id: "tailwind-web",
    title: "Tailwind CSS Full Course",
    creator: "Traversy Media",
    category: "Web Development",
    description: "Utility-first CSS for fast, beautiful landing pages and dashboards.",
    thumbnail: yt("pfaSUYa2up8"),
    difficulty: "Beginner",
    durationHours: 2,
    rating: 4.7,
    views: "1M+",
    youtubeVideoId: "pfaSUYa2up8",
    lessons: [{ id: "l1", title: "Tailwind essentials", youtubeVideoId: "pfaSUYa2up8", durationMin: 90 }],
    tags: ["tailwind", "css", "web"],
    earningTags: ["design", "freelance", "coding"],
    projectIdeas: ["Startup landing page", "Component library"],
    free: true,
  },
  {
    id: "brand-design",
    title: "Logo & Brand Identity Design",
    creator: "Will Paterson",
    category: "Graphic Design",
    description: "Logo design process, typography, and brand guidelines for clients.",
    thumbnail: yt("gYp4cKumS3o"),
    difficulty: "Intermediate",
    durationHours: 4,
    rating: 4.6,
    views: "600K+",
    youtubeVideoId: "gYp4cKumS3o",
    lessons: [{ id: "l1", title: "Logo design process", youtubeVideoId: "gYp4cKumS3o", durationMin: 40 }],
    tags: ["branding", "logo", "design"],
    earningTags: ["design", "freelance", "startup"],
    projectIdeas: ["Coffee shop rebrand", "Personal logo"],
    free: true,
  },
];

export function getCourse(id: string): Course | undefined {
  return COURSE_CATALOG.find((c) => c.id === id);
}
